name: C++ CMake Qt CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.19'
          modules: 'qtbase'

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}/lib/cmake" # Ensure CMake finds Qt

      - name: Build Project
        working-directory: ./build
        run: cmake .. && make
